/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteSomethinArgs } from "./DeleteSomethinArgs";
import { SomethinFindManyArgs } from "./SomethinFindManyArgs";
import { SomethinFindUniqueArgs } from "./SomethinFindUniqueArgs";
import { Somethin } from "./Somethin";
import { SomethinService } from "../somethin.service";

@graphql.Resolver(() => Somethin)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SomethinResolverBase {
  constructor(
    protected readonly service: SomethinService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Somethin",
    action: "read",
    possession: "any",
  })
  async _somethinsMeta(
    @graphql.Args() args: SomethinFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Somethin])
  @nestAccessControl.UseRoles({
    resource: "Somethin",
    action: "read",
    possession: "any",
  })
  async somethins(
    @graphql.Args() args: SomethinFindManyArgs
  ): Promise<Somethin[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Somethin, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Somethin",
    action: "read",
    possession: "own",
  })
  async somethin(
    @graphql.Args() args: SomethinFindUniqueArgs
  ): Promise<Somethin | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Somethin)
  @nestAccessControl.UseRoles({
    resource: "Somethin",
    action: "delete",
    possession: "any",
  })
  async deleteSomethin(
    @graphql.Args() args: DeleteSomethinArgs
  ): Promise<Somethin | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
